name: release

on:
  push:
    branches:
      - develop

jobs:
  github-pr-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Get Next Version
        id: versioning
        uses: anothrNick/github-tag-action@1.63.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_INITIAL_VERSION: 1.0.0
      - uses: MaximStone/action-github-release-pr@v3.1
        with:
          token: ${{ github.token }}
          target-branch: main
          from-branch: develop
          labels: Release
          title: Release ${{ steps.versioning.outputs.new_tag }}